{% set name = "solar-data-tools" %}
{% set version = "1.6.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/solar_data_tools-{{ version }}.tar.gz
  sha256: 5d2660f7a10b7f1657baed5754b547a6522ddb4ff47148be5d1df0f792f92ec8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - pip
    - python >={{ python_min }}
    - scipy
    - numpy
    - pandas
    - scikit-learn
    - jupyter
    - matplotlib-base
    - seaborn
    - requests
    - pvlib
    - cvxpy
    - pykml
    - haversine
    - smart_open
    - sig-decomp
    - clarabel
    - qss
    - tqdm
    - spcqe
    - dask
    - distributed
    - dask-cloudprovider
    - graphviz
    - bokeh

test:
  imports:
    - solardatatools
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/slacgismo/solar-data-tools
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Tools for performing common tasks on solar PV data signals
  doc_url: https://solar-data-tools.readthedocs.io/

extra:
  recipe-maintainers:
    - bmeyers
    - pluflou
    - MitchellAV
